name: Auto Merge and Delete Branch

on:
  pull_request_review:
    types: [submitted]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check PR approvals
      id: approval
      run: |
        APPROVALS=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '[.reviews[].state] | map(select(. == "APPROVED")) | length')
        echo "Number of approvals: $APPROVALS"
        echo "::set-output name=approvals::$APPROVALS"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Ensure PR is targeting the correct branch
      run: |
        if [[ "${{ github.event.pull_request.base.ref }}" != "develop" ]]; then
          echo "This PR must target the 'develop' branch."
          exit 1
        fi

    - name: Merge PR if approved
      if: steps.approval.outputs.approvals >= 2  # Alterado para pelo menos 2 aprovações
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --squash --delete-branch --repo ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Notify on Slack
      if: steps.approval.outputs.approvals >= 2
      uses: 8398a7/action-slack@v3
      with:
        status: good
        fields: '[{"title":"Pull Request Merged","value":"PR #${{ github.event.pull_request.number }} has been merged.","short":false}]'
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    - name: Handle Merge Errors
      if: failure()
      run: |
        echo "There was an error merging the pull request."
        exit 1
