name: Lint Code

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Especifique a versão do Node.js

      - name: Install dependencies
        run: |
          npm install  # Ou outro comando para instalar dependências

      - name: Run ESLint
        run: |
          npx eslint .  # Verifique todo o código na pasta atual
